# Load plug.kak plugin manager.
source "%val{config}/plugins/plug.kak/rc/plug.kak"

# i3 integration
# Allows :i3-new-(down|up|right|left).
plug 'delapouite/kakoune-i3' %{
    # Suggested mapping
    map global user 3 ': enter-user-mode i3<ret>' -docstring 'i3…'
}

# fzf fuzzy file finder integration
plug 'andreyorst/fzf.kak' %{
    map global normal <c-p> ':fzf-mode<ret>f' -docstring 'Search for file.'
    map global normal <c-b> ':fzf-mode<ret>b' -docstring 'Search for buffer.'
} defer fzf %{
    # Use fd since it's faster.
    set-option global fzf_file_command 'fdfind'
}

# Prompt like powerline for vim.
plug 'andreyorst/powerline.kak' defer 'powerline' %{
    powerline-separator custom '#'
    powerline-theme gruvbox
}

# Essential indentation plugin.
plug "andreyorst/smarttab.kak" defer 'smarttab' %{
    # Always expand tabs to spaces.
    set-option global expandtab
    # When `backspace' is pressed, 4 spaces are deleted at once.
    set-option global softtabstop 4
}

# Kakoune Language Server Protocol Client
# Provides auto-completion, error messages etc.
eval %sh{kak-lsp --kakoune -s $kak_session}
lsp-enable

map global user w ':write<ret>' -docstring 'Write buffer'
map global user d ':delete-buffer<ret>' -docstring 'Delete buffer'
map global user q ':quit<ret>' -docstring 'Quit'
map global user y '!xsel --input --clipboard<ret>' -docstring 'Yank to clipboard'
map global user p '!xsel --output --clipboard<ret>' -docstring 'Paste from clipboard'

# Line numbers.
add-highlighter global/ number-lines

# Show matching parentheses, braces, etc.
add-highlighter global/ show-matching

# Keep cursor at least 10 rows from the top or bottom of the window.
set-option global scrolloff 10,0

# Comment/uncomment line with #
map global normal '#' :comment-line<ret>

# Highlight current line.
set-face global CursorLine default,rgb:383838+bd
hook global RawKey .+ %{
    try %{ remove-highlighter window/cursor-line }
    try %{ add-highlighter window/cursor-line line %val{cursor_line} CursorLine }
}

colorscheme gruvbox
